Initial commit site test OSPLAY@DESKTOP-KRHR6U9 MINGW64 ~/Desktop/site_william (main) $ VGM COSPLAY@DESKTOP-KRHR6U9 MINGW64 ~/Desktop/site_william (main) $ bash: syntax error near unexpected token `(' bash: $: command not found
VGM COSPLAY@DESKTOP-KRHR6U9 MINGW64 ~/Desktop/site_william (main)
$ git push -u origin main
To https://github.com/VGM-COSPLAY/william_oudot.git
 ! [rejected]        main -> main (fetch first)
 error: failed to push some refs to
 'https://github.com/VGM-COSPLAY/william_oudot
 .git'
 hint: Updates were rejected because the remote contains work that you
 do not
 hint: have locally. This is usually caused by another repository
 pushing to
 hint: the same ref. If you want to integrate the remote changes, use
 hint: 'git pull' before pushing again.
 hint: See the 'Note about fast-forwards' in 'git push --help' for
 details.

 VGM COSPLAY@DESKTOP-KRHR6U9 MINGW64 ~/Desktop/site_william (main)
 $ ^C

 VGM COSPLAY@DESKTOP-KRHR6U9 MINGW64 ~/Desktop/site_william (main)
 $ git pull origin main --rebase
 remote: Enumerating objects: 26, done.
 remote: Counting objects: 100% (26/26), done.
 remote: Compressing objects: 100% (24/24), done.
 remote: Total 26 (delta 4), reused 12 (delta 1), pack-reused 0 (from 0)
 Unpacking objects: 100% (26/26), 24.48 MiB | 35.81 MiB/s, done.
 From https://github.com/VGM-COSPLAY/william_oudot
  * branch            main       -> FETCH_HEAD
   * [new branch]      main       -> origin/main
   Auto-merging css/home.css
   CONFLICT (add/add): Merge conflict in css/home.css
   Auto-merging css/home_mobile.css
   CONFLICT (add/add): Merge conflict in css/home_mobile.css
   Auto-merging css/main_couture.css
   CONFLICT (add/add): Merge conflict in css/main_couture.css
   Auto-merging css/main_couture_mobile.css
   CONFLICT (add/add): Merge conflict in css/main_couture_mobile.css
   Auto-merging css/main_dessin.css
   CONFLICT (add/add): Merge conflict in css/main_dessin.css
   Auto-merging css/main_dessin_mobile.css
   CONFLICT (add/add): Merge conflict in css/main_dessin_mobile.css
   Auto-merging index.html
   CONFLICT (add/add): Merge conflict in index.html
   Auto-merging js/main.js
   CONFLICT (add/add): Merge conflict in js/main.js
   Auto-merging main_couture.html
   CONFLICT (add/add): Merge conflict in main_couture.html
   Auto-merging main_dessin.html
   CONFLICT (add/add): Merge conflict in main_dessin.html
   error: could not apply 374388f... Initial commit site test
   hint: Resolve all conflicts manually, mark them as resolved with
   hint: "git add/rm <conflicted_files>", then run "git rebase
   --continue".
   hint: You can instead skip this commit: run "git rebase --skip".
   hint: To abort and get back to the state before "git rebase", run
   "git rebase --
   abort".
   hint: Disable this message with "git config set advice.mergeConflict
   false"
   Could not apply 374388f... # Initial commit site test

   VGM COSPLAY@DESKTOP-KRHR6U9 MINGW64 ~/Desktop/site_william
   (main|REBASE 1/3)
   $ git status
   interactive rebase in progress; onto 9388ba7
   Last command done (1 command done):
      pick 374388f # Initial commit site test
      Next commands to do (2 remaining commands):
         pick 8d190be # mise en page des fonds et boutons d'accueil en
	 version desktop
	  et mobile
	     pick a1ab9fe # !
	       (use "git rebase --edit-todo" to view and edit)
	       You are currently rebasing branch 'main' on '9388ba7'.
	         (fix conflicts and then run "git rebase --continue")
		   (use "git rebase --skip" to skip this patch)
		     (use "git rebase --abort" to check out the original
		     branch)

		     Changes to be committed:
		     Initial commit site test

		     # Conflicts:
		     #       css/home.css
		     #       css/home_mobile.css
		     #       css/main_couture.css
		     #       css/main_couture_mobile.css
		     #       css/main_dessin.css
		     #       css/main_dessin_mobile.css
		     #       index.html
		     #       js/main.js
		     #       main_couture.html
		     #       main_dessin.html

		     # Please enter the commit message for your changes.
		     Lines starting
		     # with '#' will be ignored, and an empty message
		     aborts the commit.
		     #
		     # interactive rebase in progress; onto 9388ba7
		     # Last command done (1 command done):
		     #    pick 374388f # Initial commit site test
		     # Next commands to do (2 remaining commands):
		     @@@
		     .git/COMMIT_EDITMSG [unix] (23:27 05/02/2026)
		     1,1 Top
		     "~/Desktop/site_william/.git/COMMIT_EDITMSG" [unix]
		     38L, 1113B